export const SET_USER = 'SET_USER';
export const SET_CONTACTS_LOADING = 'SET_CONTACTS_LOADING';
export const SET_CONTACTS_SUCCESS = 'SET_CONTACTS_SUCCESS';
export const SET_CONTACTS_FAILURE = 'SET_CONTACTS_FAILURE';

export const SET_ACTIVE_CONTACT = 'SET_ACTIVE_CONTACT';