export const SET_CHATS_LOADING = 'SET_CHATS_LOADING';
export const SET_CHATS_SUCCESS = 'SET_CHATS_SUCCESS';
export const SET_CHATS_FAILURE = 'SET_CHATS_FAILURE';

export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT';

export const SET_CONTACTS_LOADING = 'SET_CONTACTS_LOADING';
export const SET_CONTACTS_SUCCESS = 'SET_CONTACTS_SUCCESS';
export const SET_CONTACTS_FAILURE = 'SET_CONTACTS_FAILURE';

export const SET_ACTIVE_CONTACT = 'SET_ACTIVE_CONTACT';