export const SET_CHATS_LOADING = 'SET_CHATS_LOADING';
export const SET_CHATS_SUCCESS = 'SET_CHATS_SUCCESS';
export const SET_CHATS_FAILURE = 'SET_CHATS_FAILURE';

export const RESET_CHATS = 'RESET_CHATS';

export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT';

export const SET_CONTACTS_LOADING = 'SET_CONTACTS_LOADING';
export const SET_CONTACTS_SUCCESS = 'SET_CONTACTS_SUCCESS';
export const SET_CONTACTS_FAILURE = 'SET_CONTACTS_FAILURE';

export const SET_ADD_CONTACT_LOADING = 'SET_ADD_CONTACT_LOADING';
export const SET_ADD_CONTACT_SUCCESS = 'SET_ADD_CONTACT_SUCCESS';
export const SET_ADD_CONTACT_FAILURE = 'SET_ADD_CONTACT_FAILURE';

export const RESET_CONTACTS = 'RESET_CONTACTS';

export const SET_ACTIVE_CONTACT = 'SET_ACTIVE_CONTACT';